### ISSUE TITLE
Standalone svg for Hack UTK and potential for a press-kit repo

### ISSUE THREAD

**Issue by alexpawlowski** [hackutk/hackutk.github.io#1]
Hey Hack UTK!

I'm Alex Pawlowski, a grad student, and I help with organizing `KnoxDevs` among plenty of other things ;).
Do you all have an svg of your logo? If not, I can convert the black logo to an svg if you like. Also, it might be cool if you all have a `press-kit` repo for items you all will use for `VolHacks` / `HackUTK` events.

Thanks!

Alex

**Comment by jaredthecoder** [comment]
I can make a presskit repo, and I'll do that for VolHacks too!

**Comment by jaredthecoder** [comment]
I'll also upload the SVG's to both.
